services:
  nazr:
    image: markrai/nazr:latest
    container_name: nazr
    restart: unless-stopped
    ports:
      - "9161:9161"
    volumes:
      - ./data:/data
      - ./photos:/photos
    environment:
      - RUST_LOG=info
      # Add other backend environment variables here

  nazrweb:
    image: markrai/nazrweb:0.8.0
    container_name: nazrweb
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - nazr
